### ISSUE TITLE
Checking circle on equations

### ISSUE THREAD

**Issue by caotic123** [Kindelia/Kind2#30]
Suppose : 

```
Vector (t : Type) (n : Nat) : Type
Vector.empty <t> : (Vector t Nat.zero)
Vector.cons <t> (n : Nat) (v : t) (pred : (Vector t n)) : (Vector t (Nat.succ n))

Vector.length (t : Type) (n : Nat) (vec : (Vector t n)) : Nat
Vector.length t Nat.zero (Vector.empty t) = Nat.zero
Vector.length t k (Vector.cons t k value pred) = ?a
```

On the left side of the equation, the variable k appears twice, however, the term (Vector.cons t k value pred) has the type (Vector t (Nat.succ n)), when n = (Nat.succ n).

The programmer probably could lead it to an explosion, but I do not know if this is the more appropriate approach. 
A possible behavior could be Kind2 checking with an anti-circle rule or maybe avoiding non-linear rules.

**Comment by VictorTaelin** [comment]
Variables can't appear twice actually (see #31).

**Comment by caotic123** [comment]
Now I receive a friendly message error when a variable appears twice.
I think that problem is solved for now with this restriction.
Closed.
