### ISSUE TITLE
Bug on applying lambda expression

### ISSUE THREAD

**Issue by caotic123** [Kindelia/Kind2#31]
Suppose : 

```
Vector (t : Type) (n : Nat) : Type
Vector.empty <t> : (Vector t Nat.zero)
Vector.cons <t> (n : Nat) (v : t) (pred : (Vector t n)) : (Vector t (Nat.succ n))

Vector.length (t : Type) (n : Nat) (vec : (Vector t n)) : Nat
Vector.length t Nat.zero (Vector.empty t) = Nat.zero
Vector.length t (Nat.succ k) (Vector.cons t k value pred) = (Nat.succ (Vector.length t k pred)) 

Vector.index_equal_length (t : Type) (n : Nat) (vec : (Vector t n)) : (Equal Nat (Vector.length t n vec) n)
Vector.index_equal_length t n (Vector.empty t) = (Refl Nat Nat.zero)
Vector.index_equal_length t (Nat.succ k) (Vector.cons t k p pred) =  
  let rec = (Vector.index_equal_length t k pred)
  let func = (@e (Nat.succ e)) :: Nat -> Nat
  (Equal.apply Nat Nat (Vector.length t k pred) k (@e (Nat.succ e)) rec)````

```

It gives a panic error like this :
`thread 'main' panicked at 'Invalid output: 1 (String.cons 27 (String.cons 91 ...)), src/main.rs:229:5
`

And if tried to use the let as the lambda the normalizer tells me that:

```
- Expected: (Equal Nat (Nat.succ (Vector.length t k pred)) (Nat.succ k))
- Detected: (Equal Nat (func (Vector.length t k pred)) (func k))
```

But I do not know if let expression suffer from reduction, so it could not be a bug actually.

**Comment by VictorTaelin** [comment]
This was a bug with NbE getting confused by the usage of different variables with the same name. We could either rename, or show an error. I think showing an error is better, since it makes it more clear, to the user, that there is no such a thing as equally named variables (as in Idris).

Can you update and let me know if the issue is solved?

**Comment by caotic123** [comment]
Can you check this, I am getting a loop? :

```
Vector.test (t : Type) (n : Nat) (vec : (Vector t n)) : Nat
Vector.test t z g = z

Vector.test2 (t : Type) (n : Nat) (vec : (Vector t n)) : (Equal Nat (Vector.test t n vec) n)
Vector.test2 t z g = (Refl Nat z)
```

Am I doing something wrong? I think the problem is possibly linked with this commit [Reject repeated variables](https://github.com/Kindelia/Kind2/commit/21f99febab50708f6029c93def9fbc349f239957).

**Comment by VictorTaelin** [comment]
Thanks, that loop was actually caused by a bug on HVM's Rust-mode interpreter. Reporting it helped the project significantly.
