### ISSUE TITLE
Default patterns messed up the normalizer.

### ISSUE THREAD

**Issue by caotic123** [Kindelia/Kind2#32]
Consider this code of the *currently* WIKIND base, Nat/Nat.eql :

```
// Verifies if Two numbers are equal
// Example: (Nat.eql Nat.zero            Nat.zero) -> Bool.true
// Example: (Nat.eql (Nat.succ Nat.zero) Nat.zero) -> Bool.false
Nat.eql (n: Nat) (m: Nat) : Bool
Nat.eql Nat.zero     Nat.zero     = Bool.true
Nat.eql (Nat.succ n) (Nat.succ m) = (Nat.eql n m) 
Nat.eql n            m            = Bool.false
```

When you check the proof Nat.zero_not_succ we have this error : 

```
Nat.zero_not_succ <n: Nat> (e: (Equal Nat Nat.zero (Nat.succ n))): Empty
Nat.zero_not_succ n e = 
	let e = (Equal.apply @x(Nat.eql x Nat.zero) e)
	(Bool.true_not_false e)
```

The type checker actually normalizes as:
  ```let e = (Equal.apply @x(Nat.eql x Nat.zero) e) :: (Equal Bool Bool.false Bool.false)```

So, true_not_false can not be applied, however, e must have the type (Equal Bool Bool.true Bool.false) because of the default patterns :

```
....
Nat.eql n m = Bool.false
```

In order to solve this problem you have to explicit the left patterns :

```
Nat.eql (n: Nat) (m: Nat) : Bool
Nat.eql Nat.zero     Nat.zero     = Bool.true
Nat.eql (Nat.succ n) (Nat.succ m) = (Nat.eql n m) 
Nat.eql (Nat.succ n) (Nat.zero) = Bool.false
Nat.eql (Nat.zero) (Nat.succ n) = Bool.false
```

Now, the type checker knows that true_not_false is valid.

**Comment by VictorTaelin** [comment]
Thank you, very important issue.
