### ISSUE TITLE
Match.kind2 definitions derived from .type files contain repeated variables

### ISSUE THREAD

**Issue by developedby** [Kindelia/Kind2#33]
Running `kind2 derive Either/Either.type`on the following file
```
type Either <l: Type> <r: Type> {
  left  (val: l)
  right (val: r)
}
```
produces this incorrect `match.kind2` function with repeated `l` and `r` variables
```
// Automatically derived from Either/Either.type
Either.match <l: Type> <r: Type> (x: (Either l r)) <p: (x: (Either l r)) Type> (left: (val: l) (p (Either.left l r val))) (right: (val: r) (p (Either.right l r val))) : (p x)
Either.match l r (Either.left l r val) p left right = (left val)
Either.match l r (Either.right l r val) p left right = (right val)
```
It would be possible to rename the terms on the pattern match to avoid this, or we could wait until variable erasure on pattern matching is added to then produce code like this `Either.match l r (Either.left ~ ~ val) p left right = (left val)`

**Comment by VictorTaelin** [comment]
Fixed a few commits ago, thanks

**Comment by developedby** [comment]
Reopening. Now match is generated appending `_` in front of variable names, which is not valid, variables can't start with `_`. `_` should be appended zat the end for the name to be valid.

The generated code, from the same file as above:
```
// Automatically derived from Either/_.type
Either.match <l: Type> <r: Type> (x: (Either l r)) -(p: (x: (Either l r)) Type) (left: (val: l) (p (Either.left l r val))) (right: (val: r) (p (Either.right l r val))) : (p x)
Either.match l r (Either.left _l _r _val) p left right = (left _val)
Either.match l r (Either.right _l _r _val) p left right = (right _val)
```
