### ISSUE TITLE
Long loop (infinite?) while typechecking

### ISSUE THREAD

**Issue by developedby** [Kindelia/Kind2#42]
I'm trying to check the following proof
```
Nat.add.cancel_right (a: Nat) (x: Nat) (y: Nat) (e0: Equal (Nat.add x a) (Nat.add y a)) : Equal x y {
  let p0 = Nat.add.comm a x
  let p1 = Equal.chain p0 e0
  let p2 = Nat.add.comm y a
  let p3 = Equal.chain p1 p2
  let p4 = Nat.add.cancel_left a x y p2
  p4
}
```
The `p3` expression gets stuck in a loop when checking, causing an oob error after the worker's node array is exhausted (`thread 'main' panicked at 'index out of bounds: the len is 805306368 but the index is 805306368', src/builder.rs:599:11`).

Checking the expansion with `hvm debug`, it seems that it just gets longer and longer with useless duplication nodes, somewhat resembling https://github.com/Kindelia/HVM/issues/60
```
dup * b6897 = b6898;
dup * b2730 = b2731;
dup * b1090 = b1091;
dup * b870 = b871;
dup * b617 = b618;
dup * b2745 = b2746;
dup * b2847 = b2848;
dup a2038 * = a2039;
```
Maybe this program would actually eventually finish, but since it always runs out of memory I have no way of knowing if it's actually stuck in a loop or not.

I can solve this problem by avoiding type inference in `e0`, defining it's type fully as `Equal Nat ...` instead of just `Equal ...`

**Comment by VictorTaelin** [comment]
This is missing the definition of `Nat.add.cancel_left`

**Comment by developedby** [comment]
This was fixed at some point in the last week
